name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-testing:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.4' 

    - name: Install Dependencies
      run: |
        npm install -g wait-on
        npm ci 
        cd client && npm ci
        cd ../server && npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start Express Server
      env:
        SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.TEST_SUPABASE_SERVICE_ROLE_KEY }}
        PORT: 5000
      run: |
        cd server
        npm run start:ci-test & 
        wait-on http://localhost:5000

    - name: Start React Client
      env:
        REACT_APP_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
        REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.TEST_SUPABASE_ANON_KEY }}
        PORT: 3000
      run: |
        cd client
        npm run start:ci-test & 
        wait-on http://localhost:3000

    - name: Run Playwright Tests
      run: npx playwright test
      env:
        SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.TEST_SUPABASE_SERVICE_ROLE_KEY }}
        
    - name: Upload HTML report to Azure
      if: always() 
      shell: bash
      run: |
        # Creates a unique folder name for this specific test run
        REPORT_DIR='run-${{ github.run_id }}-${{ github.run_attempt }}'
        
        # Uploads the report to the $web container
        azcopy cp --recursive "./playwright-report/*" "https://kintree2026.blob.core.windows.net/\$web/$REPORT_DIR"
        
        # Prints a clickable link in the GitHub Actions logs
        echo "::notice title=HTML report url::https://kintree2026.z13.web.core.windows.net/$REPORT_DIR/index.html"
      env:
        AZCOPY_AUTO_LOGIN_TYPE: SPN
        AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
        AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
        AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'

    - name: Upload Playwright Report to GitHub Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
